# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch: 

jobs:
  douban_csv:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 44872675
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 44872675
        type: book
        format: csv
        dir: ./data/douban
        
    - name: artifact_upload
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./data
        retention-days: 1
