# .github/workflows/douban.yml
name: douban_notion
on: 
  schedule:
  - cron: "0 1 * * *"

jobs:
  douban:
    name: Douban mark data sync to notion
    runs-on: ubuntu-latest
    steps:
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: lizheming
        type: movie
        format: notion
        dir: e60642a1eb5c47d1a0259082da8e5910
        notion_token: ${{ secrets.notion_token }}
        
    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: lizheming
        type: book
        format: notion
        dir: 6ea0e15e17ce4deebb29a7fbe258d68b
        notion_token: ${{ secrets.notion_token }}
