# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch: 

jobs:
  douban_csv:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 44872675
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 44872675
        type: book
        format: csv
        dir: ./data/douban
